{
  "name": "bugbug",
  "version": "0.0.481",
  "requires_dist": [
    "amqp",
    "beautifulsoup4",
    "boto3",
    "imbalanced-learn",
    "libmozdata",
    "lmdb",
    "markdown2",
    "matplotlib",
    "mercurial",
    "microannotate",
    "mozci",
    "numpy",
    "orjson",
    "ortools",
    "pandas",
    "psutil",
    "pyOpenSSL",
    "pydriller",
    "python-dateutil",
    "python-hglib",
    "ratelimit",
    "requests",
    "rs-parsepatch",
    "scikit-learn",
    "scipy",
    "sendgrid",
    "shap",
    "tabulate",
    "taskcluster",
    "tenacity",
    "tqdm",
    "xgboost",
    "zstandard",
    "elasticsearch",
    "gensim",
    "nltk",
    "pyemd",
    "spacy",
    "wmd",
    "tensorflow"
  ],
  "error": "{\"type\": 5, \"message\": \"Failed to install: Command '['/tmp/pypi/bugbug/bin/python3', '-m', 'pip', 'install', 'bugbug']' returned non-zero exit status 1.\"}"
}